export enum ErrorCode {
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  DUPLICATE_RESOURCE = 'DUPLICATE_RESOURCE',
  FOREIGN_KEY_ERROR = 'FOREIGN_KEY_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
}
